# Generated by Django 6.1.1 on 2026-09-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'transcript',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TranscriptEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('letter_grade', models.CharField(max_length=2)),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=3)),
                ('credits_earned', models.IntegerField()),
            ],
            options={
                'db_table': 'transcript_entry',
                'managed': False,
            },
        ),
    ]
