# Generated by Django 6.1.1 on 2026-09-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
            ],
            options={
                'db_table': 'enrollment',
                'managed': False,
            },
        ),
    ]
