# Generated by Django 6.1.1 on 2026-09-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeChallan',
            fields=[
                ('challan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('generated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fee_challan',
                'managed': False,
            },
        ),
    ]
